### ISSUE TITLE
Build error related to coloredcobra

### ISSUE THREAD

**Issue by stevensonmt** [digitallyserviced/tdfgo#1]
```
go build                                                                                                  (08-17 08:58)
cmd/root.go:20:2: github.com/ivanpirog/coloredcobra@v1.0.1: replacement directory /home/chris/Documents/tdfgo/pkg/coloredcobra does not exist
```
I'm not familiar with go so not really sure how to troubleshoot this.

**Comment by stevensonmt** [comment]
Actually an easy fix. It's the go.mod file's last line. Should be a relative path since install instructions cd into the tdfgo directory.

**Comment by digitallyserviced** [comment]
thx! never really tested other than my machines lol

**Comment by stevensonmt** [comment]
Thanks for sharing it. Super cool.
