### ISSUE TITLE
Package for packages manager please?

### ISSUE THREAD

**Issue by NNBnh** [digitallyserviced/tdfgo#24]
Hi, I have come across and use this tool for a while and I really like it!

Could you package tdfgo to [Homebrew](https://brew.sh) or [Nix pkgs](https://nixos.org/manual/nixpkgs/stable) please?

Although I'm a linux user, I quite like brew recently and I think tdfgo would benefit a lot for having a brew package because brew is cross os/distro (yes is work on linux, especially on Steam Desk).

**Comment by crinklywrappr** [comment]
It's already in nix, currently on the unstable branch. Also it's in 22.11, which is in beta.
